FROM alpine:3.9

RUN apk update \
    && apk upgrade \
    && apk add bash \
    && apk add git \    
    && apk add nodejs=10.14.2-r0 \
    && apk add npm=10.14.2-r0 \
    && mkdir -p /tmp/build \
    && mkdir -p /tmp/stage \
    && mkdir -p /root/.ssh 

# keep container alive forever for building
CMD ["/bin/bash", "-c", " while true ; sleep 5; do continue ; done"]